routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AnalyzeController;
use App\Http\Controllers\HospitalController;
use App\Http\Controllers\LaboratoryController;
use App\Http\Controllers\SurgeryController;
use App\Http\Controllers\XrayCenterController;
use App\Http\Controllers\XrayController;

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale().'/admin',
        'as'=> 'admin.',
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){ 
        Route::get('/dashboard', function () {
            return view('admin.dashboard');
        });
        
        Route::resource('/analyzes', AnalyzeController::class);
        Route::resource('/laboratories', LaboratoryController::class);
        Route::post('/laboratories/assign/{laboratory}', [LaboratoryController::class,'assign'])->name('laboratories.assign');
        Route::post('/laboratories/unassign/{laboratory}', [LaboratoryController::class,'unassign'])->name('laboratories.unassign');
        Route::post('/analyzes/file-import', [AnalyzeController::class, 'fileImport'])->name('analyzes.file-import');

        Route::resource('/xrays', XrayController::class);
        Route::resource('/xrayscenters', XrayCenterController::class);
        Route::post('/xrayscenters/assign/{xraycenter}', [XrayCenterController::class,'assign'])->name('xrayscenters.assign');
        Route::post('/xrayscenters/unassign/{xraycenter}', [XrayCenterController::class,'unassign'])->name('xrayscenters.unassign');
        Route::post('/xrays/file-import', [XrayController::class, 'fileImport'])->name('xrays.file-import');

        Route::resource('/surgeries', SurgeryController::class);
        Route::resource('/hospitals', HospitalController::class);
        Route::post('/hospitals/assign/{hospital}', [HospitalController::class,'assign'])->name('hospitals.assign');
        Route::post('/hospitals/unassign/{hospital}', [HospitalController::class,'unassign'])->name('hospitals.unassign');
        Route::post('/surgeries/file-import', [SurgeryController::class, 'fileImport'])->name('surgeries.file-import');
    });

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

app/Http/Controllers/LaboratoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Provider;
use App\Models\Service;

class LaboratoryController extends Controller
{
    public function index()
    {
        $providers  = Provider::where('type','laboratory')->get();
        return view('admin.laboratories.index')->with('providers',$providers);
    }
    public function create()
    {
        return view('admin.laboratories.create');
    }
    public function store(Request $request)
    {
        Provider::create([
            'name_en' => $request->name_en,
            'name_ar' => $request->name_ar,
            'type' => 'laboratory',
        ]);

        return redirect()->route('admin.laboratories.index');
    }
    public function show($id)
    {
        $services = Service::where('type','analyze')->get();
        $provider = Provider::find($id);
        return view('admin.laboratories.show')->with('provider',$provider)->with('services',$services);
    }

    public function assign(Request $request,$id)
    {
        $services = Service::where('type','analyze')->get();
        $service =  Service::find($request->service_id);
        $provider = Provider::find($id);
        $provider->services()->attach($request->service_id,['original_price'=>$request->original_price,'sell_price'=>$request->sell_price,'purchase_price'=>$request->sell_price]);
        return redirect()->route('admin.laboratories.show',$provider)->with('provider',$provider)->with('services',$services);
    }

    public function unassign(Request $request,$id)
    {
        $services = Service::where('type','analyze')->get();
        $service =  Service::find($request->service_id);
        $provider = Provider::find($id);
        $provider->services()->detach($request->service_id);
        return redirect()->route('admin.laboratories.show',$provider)->with('provider',$provider)->with('services',$services);
    }

}

resources/views/admin/laboratories/create.blade.php
@extends('admin.layouts.master')
@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Laboratories Create</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Laboratories Create</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Small boxes (Stat box) -->
                <div class="row">
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Create Laboratory</h3>
                            </div>
                            <!-- /.card-header -->
                            <form action="{{ route('admin.laboratories.store') }}" method="POST">
                                @csrf
                                <div class="card-body">
                                  <div class="form-group">
                                    <label for="name_en">Name EN</label>
                                    <input type="text" class="form-control" name="name_en" placeholder="Enter Name in English">
                                  </div>
                                  <div class="form-group">
                                    <label for="name_ar">Name AR</label>
                                    <input type="text" class="form-control" name="name_ar" placeholder="Enter Name in Arabic">
                                  </div>
                                </div>
                                <!-- /.card-body -->
                
                                <div class="card-footer">
                                  <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                              </form>
                            <!-- /.card-body -->
                           
                        </div>
                    </div>
                </div>
                <!-- /.row -->

            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

resources/views/admin/laboratories/index.blade.php
@extends('admin.layouts.master')
@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Laboratories List</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Laboratories List</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Small boxes (Stat box) -->
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Laboratories List</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <div style="margin-bottom: 10px; float: right;">
                                    <a href="{{ route('admin.laboratories.create') }}" class="btn btn-primary">Add
                                        Laboratory</a>
                                </div>
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th style="width: 10px">#</th>
                                            <th>Name</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($providers as $index => $provider)
                                            <tr>
                                                <td>{{ $index + 1 }}</td>
                                                <td>
                                                    @if (LaravelLocalization::getCurrentLocale() == 'ar')
                                                        {{ $provider->name_ar }}
                                                    @else
                                                        {{ $provider->name_en }}
                                                    @endif
                                                </td>
                                                <td>
                                                  
                                                    <a href="{{ route('admin.laboratories.show',$provider) }}"
                                                        class="btn btn-primary">Assign Analyze</a>
                                                </td>
                                            </tr>
                                        @endforeach

                                    </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->

                        </div>
                    </div>
                </div>
                <!-- /.row -->

            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

resources/views/admin/laboratories/show.blade.php
@extends('admin.layouts.master')
@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Assign Analyze to {{ $provider->name_en }}</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Assign Analyze</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Small boxes (Stat box) -->
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Analyzes List</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">

                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th style="width: 10px">#</th>
                                            <th>Name</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($services as $index => $service)
                                            <tr>
                                                <td>{{ $index + 1 }}</td>
                                                <td>
                                                    @if (LaravelLocalization::getCurrentLocale() == 'ar')
                                                        {{ $service->name_ar }}
                                                    @else
                                                        {{ $service->name_en }}
                                                    @endif
                                                </td>
                                                <td>
                                                    @if ($provider->services()->where('service_id', $service->id)->first())
                                                        <form action="{{ route('admin.laboratories.unassign',$provider) }}" method="POST">
                                                            @csrf
                                                            <input type="hidden" value="{{ $service->id }}" name="service_id">
                                                            <button type="submit" class="btn btn-danger">
                                                                Unassign
                                                            </button>
                                                        </form>
                                                    @else
                                                        <button  type="button"
                                                            data-id="{{ $service->id }}" class="assign_button btn btn-primary"
                                                            data-toggle="modal" data-target="#modal-default">
                                                            Assign
                                                        </button>
                                                    @endif


                                                </td>
                                            </tr>
                                        @endforeach

                                    </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
                            <div class="modal fade" id="modal-default">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title">Default Modal</h4>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <form action="{{ route('admin.laboratories.assign', $provider->id) }}"
                                            method="POST">
                                            @csrf
                                            <div class="modal-body">
                                                <input type="hidden" id="service_id" name="service_id">
                                                <div class="form-group">
                                                    <label for="original_price">Original Price</label>
                                                    <input type="number" class="form-control" name="original_price"
                                                        placeholder="Enter Original Price">
                                                </div>
                                                <div class="form-group">
                                                    <label for="sell_price">Sell Price</label>
                                                    <input type="number" class="form-control" name="sell_price"
                                                        placeholder="Enter Sell Price">
                                                </div>
                                                <div class="form-group">
                                                    <label for="purchase_price">Purchase Price</label>
                                                    <input type="number" class="form-control" name="purchase_price"
                                                        placeholder="Enter Purchase Price">
                                                </div>
                                            </div>
                                            <div class="modal-footer justify-content-between">
                                                <button type="button" class="btn btn-default"
                                                    data-dismiss="modal">Close</button>
                                                <button type="submit" class="btn btn-primary">Save changes</button>
                                            </div>
                                        </form>
                                    </div>
                                    <!-- /.modal-content -->
                                </div>
                                <!-- /.modal-dialog -->
                            </div>
                            <!-- /.modal -->
                        </div>
                    </div>
                </div>
                <!-- /.row -->

            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

@section('scripts')
    <script>
        $('.assign_button').on('click', function() {
            const button = $(this)
            $('#service_id').val(button.data('id'));
        });
    </script>
@endsection